plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://writing-machine.github.io
baseurl: /grokf

title: Writing Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Writing-Machine
  verb: Writing
  instructions_file: writing.txt
  token: grok.txt
  apiUrl: https://api.x.ai/v1/chat/completions

app:
  worker_name: grokapi.js

lm:
  model: grok-4
  max_completion_tokens: 1024
  temperature: 1.0
  top_p: 0.95


github_settings:
  owner: writing-machine
  repo: writing_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
